service: serverless-nest-microservice-layer
frameworkVersion: '3'

provider:
  name: aws
  profile: ekrenz-serverless

layers:
  base:
    name: 'base-prod-dependencies'
    compatibleRuntimes:
      - 'nodejs18.x'
    package:
      artifact: nodejs.zip