service: serverless-nest-microservice-layer
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  profile: ${env:FUNC_PREFIX}

layers:
  base:
    name: 'base-prod-dependencies'
    compatibleRuntimes:
      - 'nodejs18.x'
    package:
      artifact: nodejs.zip